export const Icons = {
  docker: 'mdi:docker',
  gitlab: 'mdi:gitlab',
  nextcloud: 'tabler:brand-nextcloud',
  vscode: 'tabler:brand-vscode',
  plus: 'hugeicons:dashboard-square-edit',
  delete: 'hugeicons:delete-02',
  edit: 'hugeicons:edit-01',
  system: 'hugeicons:system-update-01',
  truck: 'hugeicons:container-truck',
  play: 'hugeicons:play-square',
  stop: 'hugeicons:stop-circle',
  restart: 'hugeicons:circle-arrow-data-transfer-horizontal',
  running: 'hugeicons:running-shoes',
  globe: 'hugeicons:globe-02',
  table: 'hugeicons:property-new',
  home: 'hugeicons:home-01',
  serverStack: 'hugeicons:server-stack-01',
  clock: 'hugeicons:clock-03',
  horizontalKeyframe: 'hugeicons:keyframe-align-horizontal',
  userSquare: 'hugeicons:user-square',
  userCircle: 'hugeicons:user-circle',
  lockKey: 'hugeicons:lock-key',
  eye: 'hugeicons:eye',
  viewOff: 'hugeicons:view-off',
  flyingHuman: 'hugeicons:flying-human',
  logout: 'hugeicons:logout-01',
  cpu: 'hugeicons:cpu',
  disk: 'hugeicons:floppy-disk',
} as const

export type IconName = keyof typeof Icons
